import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer.jsx";
export default function Home({children}) {
  return (
    <div>
      <Head>
        <title>Buy Online</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar/>
      {children}
      <Footer/>
    </div>
  );
}
